### ISSUE TITLE
Replace RSS subscribe with mailchimp subscription dialog

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/blog#14]
Bottom left of http://blog.pslmodels.org
![image](https://user-images.githubusercontent.com/6076111/100147225-e9847c00-2e4f-11eb-806b-2b1a83ccfd76.png)

Replace with form from bottom of http://pslmodels.org/

![image](https://user-images.githubusercontent.com/6076111/100147341-16d12a00-2e50-11eb-91e5-cea2c2baf9ab.png)

cc @Peter-Metz

**Comment by Peter-Metz** [comment]
@MaxGhenis I looked into this a bit this morning, and it seems that other people are running into similar issues with both [fastpages](https://github.com/fastai/fastpages/issues/453) and [jekyll/minima](https://github.com/jekyll/minima/issues/553).  The gist is that jekyll/minima doesn't have a built-in way to customize the footer. I would be curious to see if we could get around this by saving our own footer to `_includes/footer.html`. I can give this a shot in the next few days.

**Comment by MaxGhenis** [comment]
Fixed in #28
