### ISSUE TITLE
Omit categories from post URLs

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/blog#17]
We're currently using the default URL settings, which add the category(ies) to the URL, e.g. http://blog.pslmodels.org/demo-days/2020/11/23/tax-cruncher.html.

This isn't great with one category, but it's especially bad with multiple categories, as @jdebacker added to the CCC post in #16. That URL would read http://blog.pslmodels.org/demo-days/cost-of-capital-calculator/business-taxation/corporate-income-tax/2020/12/02/ccc.html.

Per [this Fastpages forum post](https://forums.fast.ai/t/no-badges-and-post-urls-look-funky-they-are-using-categories/67720/11), URL structures can be changed globally via [Jekyll instructions](https://jekyllrb.com/docs/permalinks). For example, URLs could read http://blog.pslmodels.org/2020/12/02/ccc.html, or even something like http://blog.pslmodels.org/ccc. This will break links from past posts, but I think we're early enough that it'd be worth doing now. WDYT @jdebacker @MattHJensen @hdoupe?

**Comment by hdoupe** [comment]
@MaxGhenis Let's drop the tags from the URL path. 

In addition to being clunky, we may want to rename a category or come up with a new category that a previous post would fall into.

**Comment by jdebacker** [comment]
Yes - I agree with @hdoupe   Thanks for looking into this @MaxGhenis

**Comment by MaxGhenis** [comment]
Sounds good. Looking at [some](https://moz.com/community/q/blog-article-url-with-or-without-date) [guides](https://www.searchenginenews.com/sample/content/should-i-remove-the-dates-in-my-blog-urls-yes) I think we should also remove the date from the URL, and instead make the URL text descriptive, e.g. blog.pslmodels.org/demo-day-3-ccc. What do you think?

**Comment by hdoupe** [comment]
@MaxGhenis I'm OK with removing the dates. They are in the post after all.

Also, fwiw I just picked three tech blogs at random and got three different url structures:
- https://blog.cloudflare.com/improving-the-resiliency-of-our-infrastructure-dns-zone/
- https://dropbox.tech/infrastructure/asynchronous-task-scheduling-at-dropbox
- https://hacks.mozilla.org/2020/11/firefox-83-is-upon-us/

So, I don't think we can go wrong here (well except for having multiple categories in a URL).

**Comment by jdebacker** [comment]
> So, I don't think we can go wrong here (well except for having multiple categories in a URL).

Agree!  Don't mind dates in URL, but it needs to be short and easy to make it unique (either date or demo day number should help with that).
