### ISSUE TITLE
2020 Year in Review post

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/blog#21]
We could take the top updates from the 2020 PSL newsletters and aggregate them together.

**Comment by jdebacker** [comment]
Some recent ones that could be considered:
* New cataloged models in the Library: microdf (a tool for working with survey microdata) and OpenFisca-UK (a UK tax and transfer microsimulation model).
* PSL Demo Day series 
* The PSL blog
* External presentations of PSL model projects (e.g., PyData Global Conference)
* PSL models use by academics, think tanks, and others
* Tax-Calculator 3.0 (and other major releases)
* Open Collective Foundation fiscal sponsorship

I'm sure there's more...

**Comment by MaxGhenis** [comment]
Closed in #23
