### ISSUE TITLE
Host at blog.pslmodels.org

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/blog#3]

**Comment by MaxGhenis** [comment]
@hdoupe could you do this on Cloudflare? As suggested by @MattHJensen.

Current one with the first post is up at https://pslmodels.github.io/blog/

**Comment by hdoupe** [comment]
Definitely. I need to do these things:

- [ ] add a cname file to the publish branch like this one: https://github.com/compute-tooling/compute-studio/blob/gh-pages/CNAME
- [ ] update the gh pages url in the repo settings.
- [ ] add the entry on cloudflare with the gh pages ip

**Comment by hdoupe** [comment]
@MaxGhenis The URL is up! https://blog.pslmodels.org/

What branch are you planning to deploy from? Still `gh-pages`?

![Screenshot from 2020-11-10 17-43-03](https://user-images.githubusercontent.com/9206065/98742311-33fbf800-237c-11eb-8d13-63e9a7e8be6a.png)

**Comment by MaxGhenis** [comment]
Yes gh-pages, but I think some js isn't loading right, it looks different
from how it looked on GitHub.io. It should look like fastpages.fast.ai.

**Comment by hdoupe** [comment]
@MaxGhenis sorry for the confusion on this. It looks like the `/blog` base name isn't being updated.

In the `gh-pages` branch:

https://github.com/PSLmodels/blog/blob/6e713fb3401d8844d16561b975e2e91494dc67ce/index.html#L17-L21

But the file is actually at: https://blog.pslmodels.org/assets/css/style.css
Not at: http://blog.pslmodels.org/blog/assets/css/style.css

I've updated the url base name configuration everywhere I can think to...Do you know why the `index.html` file isn't getting updated with it? Is it supposed to be re-written on each deploy?

**Comment by MaxGhenis** [comment]
@hdoupe yes, I think many of the files get rewritten on PRs, e.g. via the GH Action at https://github.com/PSLmodels/blog/blob/master/.github/workflows/ci.yaml.

**Comment by MaxGhenis** [comment]
Fixed, thanks @hdoupe!
