### ISSUE TITLE
Add post on first Demo Days

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/blog#4]
See my [placeholder Markdown](https://raw.githubusercontent.com/PSLmodels/blog/d0914ee7bebfbc7a3f1e872cc6f6ea21ba74e887/_posts/2020-11-04-first-demo-day.md) from #1

**Comment by MattHJensen** [comment]
How does this look? https://hackmd.io/@5zG_0RMbQZi63yqCWg_RmQ/S1g2v6yrP/edit

**Comment by MaxGhenis** [comment]
Do you want to add a sentence or two describing the scope and intent of Demo Days? Otherwise LGTM.

**Comment by MattHJensen** [comment]
> Do you want to add a sentence or two describing the scope and intent of Demo Days?

Title and context seem pretty helpful here. I'm inclined to leave it as it is.

**Comment by MaxGhenis** [comment]
@MattHJensen sounds good, could you file a PR to add it to https://github.com/PSLmodels/blog/tree/master/_posts ?

**Comment by MaxGhenis** [comment]
@MattHJensen friendly ping now that @hdoupe got the blog working on the site.
