### ISSUE TITLE
Blog is down

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/blog#94]
https://blog.pslmodels.org as linked from https://pslmodels.org is down

**Comment by jdebacker** [comment]
Dang it!  I spent a lot of time learning and transferring everything over from Fast Pages to Quarto and had this working. 

Thanks for pointing this out, @MaxGhenis. Unfortunately, I won't have time to look at it for at least a week.

**Comment by jdebacker** [comment]
@MaxGhenis -- can you take a look now?  Seems that somehow the custom domain setting got removed.  I updated and it now loads for me a blog.pslmodels.org

**Comment by MaxGhenis** [comment]
Looks good!
